In [1]:
import numpy as np

In [2]:
myarr= np.array([[3,6,4,5,7]], np.int64)

In [3]:
myarr

array([[3, 6, 4, 5, 7]], dtype=int64)

In [4]:
myarr[0 , 3]

5

In [5]:
myarr[0,4]

7

In [6]:
myarr.shape

(1, 5)

In [7]:
myarr.dtype

dtype('int64')

# Creating arrays through numpy




In [8]:
zeros= np.zeros((2,5))
#gives an array of zeros

In [9]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
arange= np.arange(20)
#range funtion

In [11]:
arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
linspace= np.linspace(1,100,20)
#creates an array of equal 20 elements with 1 as the first element
#and 100 as the last element 
#and all other elements are in AP

In [13]:
linspace

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [14]:
linspace.dtype

dtype('float64')

In [15]:
emp= np.empty((4,6))
#creates an array with random nos.

In [16]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        2.78146625e-307, 1.33511018e-306, 1.33511969e-306],
       [6.23037996e-307, 6.23053954e-307, 9.34609790e-307,
        8.45593934e-307, 9.34600963e-307, 1.86921143e-306],
       [6.23061763e-307, 8.90104239e-307, 6.89804132e-307,
        9.34605716e-307, 1.37962456e-306, 1.42418172e-306],
       [2.04712906e-306, 7.56589622e-307, 1.11258277e-307,
        8.90111708e-307, 2.11389826e-307, 1.11260619e-306]])

In [17]:
emp_like= np.empty_like(linspace)

In [18]:
emp_like

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [19]:
ide= np.identity(3)
#creates an identity matrix

In [20]:
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
arr= np.arange(100)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [23]:
arr.reshape(5,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [24]:
arr=arr.ravel()
#ravel converts 2-D array to 1-D array

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [26]:
arr.shape

(100,)

# AXIS:-

axis=0   for rows

axis=1   for columns

       ---------> axis=1
       
   [ 1    2     3
 ^     
 '     4    5     6
 '     
 '     7    8     9]
 '
axis=1

In [27]:
list= [(1,2,3),(4,5,6),(7,8,9)]

In [28]:
list

[(1, 2, 3), (4, 5, 6), (7, 8, 9)]

In [29]:
ar= np.array(list)

In [30]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
ar.sum(axis=0)
#sum of elements of row1,row2,row3

array([12, 15, 18])

In [32]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [33]:
ar.T
#Transpose of matrix

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [34]:
ar.flat
#for iteration (for loop etc.)

In [35]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [36]:
ar.ndim
#dimension of array

2

In [37]:
ar.size

9

In [38]:
ar.nbytes
#total bytes consumed

36

In [39]:
one= np.array([1,3,4,654,6])

In [40]:
one

array([  1,   3,   4, 654,   6])

In [41]:
one.argmax()
#index where maximum element is present

3

In [42]:
one.argmin()
#index where minimum element is present

0

In [43]:
one.argsort()
#for sorting in ascending order(shows the index)

array([0, 1, 2, 4, 3], dtype=int64)

In [44]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
ar.argmin()
#index where minimum element is found(in ar min element=1 and its index=0)

0

In [46]:
ar.argmax()
#index where max element is found(in ar max element=9 and its index=8)

8

In [47]:
ar.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [48]:
ar.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [49]:
ar.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [50]:
ar.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [51]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [52]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [53]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [55]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
ar2= np.array([[1,2,5],[7,4,8],[5,2,7]])

In [57]:
ar2

array([[1, 2, 5],
       [7, 4, 8],
       [5, 2, 7]])

In [58]:
ar+ar2
#addition of matrix

array([[ 2,  4,  8],
       [11,  9, 14],
       [12, 10, 16]])

In [59]:
ar*ar2
#multiplication of 2 matrix(element wise)

array([[ 1,  4, 15],
       [28, 20, 48],
       [35, 16, 63]])

In [60]:
np.sqrt(ar)
#square root of each elements of array

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [61]:
ar.sum()

45

In [62]:
ar.max()

9

In [63]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
np.where(ar<5)

(array([0, 0, 0, 1], dtype=int64), array([0, 1, 2, 0], dtype=int64))

In [65]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [66]:
np.count_nonzero(ar)

9

In [67]:
import sys

In [68]:
py_ar= [0,4,55,2]

In [69]:
np_ar=np.array(py_ar)

In [70]:


py_ar


[0, 4, 55, 2]